#index:
#    path: /
#    controller: App\Controller\DefaultController::index
Api_login_check:
  path: /api/login_check
  methods:  [POST]

gesdinet_jwt_refresh_token:
  path: /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh
  methods:  [POST]

api:
  prefix: /api
  resource: '../src/Controller/Rest'


